### ISSUE TITLE
실습과제 2 PK전략

### ISSUE THREAD

**Issue by anyjava** [anyjava/jpa-book#5]
## 상세내용
- 회원객체의 식별자를 숫자(Long)로 변경
- IDENTITY 전략을 사용 - 134p
- SEQUENCE 전략을 사용 -136p
- TABLE 전략을 사용 - 139p
- AUTO 전략을 사용 - 142p

**Comment by anyjava** [comment]
INDEITY 전략을 사용할때 쿼리문의 변화는 없음 ( AUTO_INCREMENT 를 사용하기 때문 )

**Comment by anyjava** [comment]
![image](https://cloud.githubusercontent.com/assets/953526/13921724/9d83bc8e-efbc-11e5-91fc-e7496fe874c7.png)
SEQUENCE 테이블이 생성되는걸 확인가능

**Comment by anyjava** [comment]
![image](https://cloud.githubusercontent.com/assets/953526/13921820/239715d2-efbd-11e5-9fb5-7b724d1dd67b.png)
키 테이블을 select  하고 insert 하고 update 하고 엄청난 작업들이 잃어남.. (속도가 느린 이유!!)

**Comment by philo-grammer** [comment]
:+1:

**Comment by anyjava** [comment]
![image](https://cloud.githubusercontent.com/assets/953526/13921928/9bdcdc3e-efbd-11e5-9d48-32445b1a1d51.png)
- AUTO 는 H2 데이터베이스에서는 sequence 전략을 사용하는 군요!
